"""Create table user

Revision ID: 12d7c28f3733
Revises: 5ade043126e7
Create Date: 2024-10-14 21:53:28.708725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d7c28f3733'
down_revision: Union[str, None] = '5ade043126e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('auth_idx', 'users', ['email', 'password'], unique=False)
    op.create_index('email_idx', 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email_idx', table_name='users')
    op.drop_index('auth_idx', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
