"""Add roles enum type and role column

Revision ID: 37f8ed090dd1
Revises: adc948484ab4
Create Date: 2024-11-11 22:35:02.627914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '37f8ed090dd1'
down_revision: Union[str, None] = 'adc948484ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

roles_enum = ENUM('admin', 'user', name='roles_enum')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    roles_enum.create(op.get_bind())
    op.add_column('users', sa.Column('role', roles_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    roles_enum.drop(op.get_bind())
    # ### end Alembic commands ###
